### ISSUE TITLE
Not open source.

### ISSUE THREAD

**Issue by 9600** [jerry-D/SYMPL-GP-GPU-Compute-Engines#1]
This project is described as being open source, but the licence is pretty restrictive and discriminates against field of endeavour, meaning that it technically is not. See (6):

https://opensource.org/osd-annotated

**Comment by jerry-D** [comment]
Who are you?  "open source" means whatever "I" say it means.  Apparently you read the LICENSE.txt, so obviously, "open source" as it relates to my license and subject work, does not mean what you thought it means.  If "Open Source.org" can say it means one thing, I can say it means whatever I say it means, they don't own the two words, "open source".  You read my license.  So what is the problem?  If you don't like the terms of my license, then don't use the software.

**Comment by brouhaha** [comment]
I can call my car a horse, but it doesn't make it so. Your license is very much contrary to what anyone understands as open source. As you suggest, I won't use the software, but nevertheless you are deliberately being misleading.

**Comment by 9600** [comment]
I'm afraid that you are attempting to redefine something, that has come to be widely understood by millions of people the world over to mean something very different from your _interpretation_. The ability to use it in commercial products being a fundamental principle of open source, absolutely key to its success and the reason why the value of the marketplace is measured in billions.

I'd respectfully suggest that a more fitting term might be "open shareware", or "open advertisingware".

Who are the Open Source Initiative? Just the organisation that was set up by the people who coined the term "open source", that steward the definition and approve licences that meet the criteria. Oh, by the way, I'd suspect that your licence would fail this.

**Comment by jerry-D** [comment]
You opened and read the LICENSE.txt file because you wanted to know what "I" mean by "open source".  You fulfilled your obligation to read and understand the LICENSE.txt file.  You now know that, for the purposes of subject license, "open source" does not mean what "Open Source.org" says it means, but rather, "open source" means what "I" say it means. Consequently, you have not been mislead and the substance of subject LICENSE.txt file is not misleading.

Not an issue of "interpretation".  It's an issue of "definition".  The work's author/owner defines the terms of its own LICENSE, not some so and so organization,  If, for what ever reason, an author elects to license his work under the "Open Source.org" license, that's his business and his right.  

I have elected to license my works under my own license under my own terms, which is my business and my right and mine alone.  So don't waltz onto my website and tell me how to define my terms or license my software.  The issue is closed.  Move on.

**Comment by 9600** [comment]
As you very rightly point out, you are free to use whatever licence you please and this is not in dispute. However, calling a licence with a non-commercial clause _open source_ is akin to selling a vegan bacon sandwich that contains real pig flesh.

**Comment by jerry-D** [comment]
I never said this was an "Open Source.org" "open source" license.  Subject
license is an "open source" license, but expressly not an "Open Source.org"
"open source" license..  "Open Source.org" does not own the term, "open
source", nor does it have exclusive dominion over such term.  If you don't
like the terms of "my" "open source" license, then don't use or
re-distribute the software.  Issue closed. Move on.

**Comment by rah2501** [comment]
"don't waltz onto my website and tell me how to define my terms"

Fair enough but why did you use the term "open source" in the first place if you're using it differently to how everyone else uses it?

All of the words and phrases we are using here have meanings associated with them which for the most part correspond between two people.  If they don't correspond, we can't communicate.  For example, people generally use the word "shoe" to refer to the things you wear on your feet.  However, if I start to refer to that thing you see when you look up outside with the word "shoe" instead of "sky", that will make it very difficult to communicate.

You're using the phrase "open source" in a way which is different to how everyone else uses it.  That makes communication a problem.

Were you aware that the meaning you associated with the phrase "open source" differed from how everyone else used it, before this issue was raised?  If so, why did you deliberately choose to attach a non-normal meaning to it?

**Comment by jerry-D** [comment]
Every license, every contract that ever existed, the "licensor" defines his
own terms.  He can say red means black, cat means dog.  Subject license is
not an "Open Source.org" "open source" license, it is "my" "open source"
license.  "I" define the terms, not some organization located who knows
where.  "If" I had licensed my software under the "Open Source.org" "open
source" license, you would have a point.  But since I am licensing under
"my" own "open source" license, then "open source" means what "my" license
says and expressly "not" what the "Open Source.org" "open source" license
says.

**Comment by rah2501** [comment]
But why are you describing it using the phrase "open source" in the first place?

**Comment by jerry-D** [comment]
You clicked on the "LICENSE.txt" link because you wanted to know what "I"
meant by "open source", thereby fulfilling "your" obligation to read and
understand the license.  You now know what "I" mean by "open source".  For
your information, here is the link to the FloPoCo website, in that SYMPL
GP-GPU and RISC CPU presently employ FloPoCo-generated floating-point
operators:

http://flopoco.gforge.inria.fr

Here is an excerpt of "their" "open-source" license.  In short, "open
source" means what the "licensor" says it means.  Such use of "open source"
is not misleading and you have not been mislead because you now know what
the "licensor" means by "open source".  "Open Source.org" does not own the
term "open source", nor does it have exclusive dominion over its use.  The
problem is, you held a false belief or false understanding of what "open
source" means.  "open source" means whatever the licensor says it means.
If you don't agree with the licensor's terms, then do not use or distribute
the software.  Just like clicking on the "I Accept" button on
shrink-wrapped software.  Either you agree with the terms or you don't.

"Distribution

FloPoCo is open-source. Contributions are welcome!

Installation instructions (including one-line install for Ubuntu) are
provided in the user manual
http://flopoco.gforge.inria.fr/flopoco_user_manual.html.

The intent of the authors is to distribute FloPoCo as free software (in the
FSF AGPL sense), while imposing that the source code generated by FloPoCo
is also free software (also AGPL-like). The (A)GPL doesn't seem to allow
that, so it seems we have to invent something.

Current state of the license is therefore "all right reserved", which just
means that the distribution terms are still being decided by the copyright
owners (a consortium of the employers of the authors).

If this is a problem for your application, we are ready to negociate a
commercial license: contact us <Florent.de.Dinechin %C3%A0 ens.lyon.fr>."

:

**Comment by rah2501** [comment]
> here is the link to the FloPoCo website

You haven't answered my question.  Why are _you_ using the phrase "open source" in the first place?  Are you saying you started using the phrase "open source" to describe your project because the FloPoCo project uses it and you copied them?

**Comment by jerry-D** [comment]
Because "open source" is convenient two-word adjective and this is how "I"
elected to best describe "my" license.  Any more of your questions along
these lines will go unanswered. Move on.

**Comment by rah2501** [comment]
"convenient two-word adjective"

LOL
